### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by mnekx** [harlexkhal/Microverse-Porfolio-Website#14]
It has been realy hard finding an issue with this site because of the good job you have done with it, so kudos 💯 

Could the title be better? I mean so that the site expresses what exactly is it for. It may start with something specific such as your name.

**Comment by Bavon101** [comment]
@harlexkhal I think your site would be more optimized for web crawlers if you used `CSS background image styling `instead of `img` tag, Cheers 🐱‍🏍

**Comment by saied2035** [comment]
great work you did. you made a really responsive projects 🥇. just optional change to do it's to good practice to give icons width.
and again you really did a great work 👏 .

**Comment by harlexkhal** [comment]
Thanks, guys, I've noted all of the changes. and would consider all of the suggestions and issues raised.
