### ISSUE TITLE
Morning session | peer to peer code review

### ISSUE THREAD

**Issue by vikipretium** [harlexkhal/Microverse-Porfolio-Website#6]
### Requirements of contact form 

- contact form is in the `section` tag
- Changes needed : need to change the `section` tag to `footer` tag of the contact form.

**Comment by zmekonnen251** [comment]
- The social media links are not working. You should have to make sure you used a working link.

**Comment by mnekx** [comment]
The site is well done, it is very hard to find an issue. But, see 
![screeneshot](https://user-images.githubusercontent.com/22321030/149284811-50ed126f-295e-4cbe-adcb-6fd9dabd0f6c.png). I think it would be better semantically to use a section tag on the div inside the li tag that contains h3 header.

**Comment by mnekx** [comment]
## .language class
consider screeshot below
![image](https://user-images.githubusercontent.com/22321030/149285824-67d65049-0462-4bda-b901-74ed66170645.png)
Since the class .languages does not have responsibilities, it would be better if it was removed I think.

**Comment by harlexkhal** [comment]
Thanks guys i've noted all of your review feedback and would definitely work on them )))
